// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MyMLAppML.Model
{
    public class ModelInput
    {
        [ColumnName("review"), LoadColumn(0)]
        public string Content { get; set; }


        [ColumnName("label"), LoadColumn(1)]
        public string Label { get; set; }


    }
}
